### ISSUE TITLE
Display problem within a Simulator

### ISSUE THREAD

**Issue by iheos** [iheos/iheos-toolkit3#120]
Originally reported by: **Bill Majurski (Bitbucket: [bmajur](https://bitbucket.org/bmajur), GitHub: Unknown)**

---

A simulator contains two top-level assets:  config.xml (along with its config.props.txt property file) and site.xml (along with its site.props.txt file).  In the log browser, site displays properly while config shows a "The document is missing!" message. The repository generating the error is attached.

---
- Bitbucket: https://bitbucket.org/iheos/defunct-toolkit-prototype/issue/120

**Comment by iheos** [comment]
_Original comment by_ **Sunil Bhaskarla (Bitbucket: [skbhaskarla](https://bitbucket.org/skbhaskarla), GitHub: [skbhaskarla](https://github.com/skbhaskarla))**:

---

I found out the issue causing this problem. It is related to the XML content and how the XML formatter handles it. If the XML content has single quoted attributes, then the XmlFormatter has a problem that causes an exception to be thrown as shown below (this was after the code was updated to print a stack trace):

[ERROR] java.lang.StringIndexOutOfBoundsException: String index out of range: 219
[ERROR]         at java.lang.String.substring(String.java:1955)
[ERROR]         at gov.nist.hit.ds.utilities.xml.XmlFormatter.findNextParm(XmlFormatter.java:235)
[ERROR]         at gov.nist.hit.ds.utilities.xml.XmlFormatter.findNextParm(XmlFormatter.java:239)
[ERROR]         at gov.nist.hit.ds.utilities.xml.XmlFormatter.newOpen(XmlFormatter.java:317)
[ERROR]         at gov.nist.hit.ds.utilities.xml.XmlFormatter.run(XmlFormatter.java:345)
[ERROR]         at gov.nist.hit.ds.utilities.xml.XmlFormatter.htmlize(XmlFormatter.java:501)
[ERROR]         at gov.nist.hit.ds.utilities.xml.XmlFormatter.htmlize(XmlFormatter.java:505)
[ERROR]         at gov.nist.hit.ds.repository.ContentHelper.getContent(ContentHelper.java:110)
[ERROR]         at gov.nist.hit.ds.repository.rpc.search.server.RepositoryServiceImpl.getAssetTxtContent(RepositoryServiceImpl.java:86)

The XML content:
<actor type='docrec'>
  <transaction name='prb'>
    <endpoint value='http://localhost:9080/xdstools3/sim/1/docrec/prb' />
    <settings>
      <boolean name='schemaCheck' value='true' />
      <boolean name='modelCheck' value='false' />
      <boolean name='codingCheck' value='false' />
      <boolean name='soapCheck' value='true' />
      <text name='msgCallback' value='http://localhost:9080/xdstools3/log/x' />
    </settings>
    <webService value='prb' />
  </transaction>
  <transaction name='prb'>
    <endpoint value='https://localhost:9080/xdstools3/sim/1/docrec/prb' />
    <settings>
      <boolean name='schemaCheck' value='true' />
      <boolean name='modelCheck' value='false' />
      <boolean name='codingCheck' value='false' />
      <boolean name='soapCheck' value='true' />
      <text name='msgCallback' value='http://localhost:9080/xdstools3/log/x' />
    </settings>
    <webService value='prb_TLS' />
  </transaction>
</actor>
