### ISSUE TITLE
Groovy error at runtime inside IntelliJ on develop branch

### ISSUE THREAD

**Issue by iheos** [iheos/iheos-toolkit3#157]
Originally reported by: **Diane Azais (Bitbucket: [dazais](https://bitbucket.org/dazais), GitHub: [dazais](https://github.com/dazais))**

---

Bill, any idea where this comes from? I am getting this on the develop branch when trying to run Xdstools3 inside IntelliJ. It is linked to toolkit-core since there is no groovy used in xdstools3.

Information:Using javac 1.7.0_71 to compile java sources
Information:Groovyc: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jetbrains.groovy.compiler.rt.GroovycRunner.main(GroovycRunner.java:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:121)
Caused by: java.lang.NoClassDefFoundError: org/xmlpull/v1/XmlPullParser
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
    at java.lang.Class.getDeclaredMethods(Class.java:1860)
    at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:328)
    at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:262)
    at org.codehaus.groovy.ast.ClassNode.getDeclaredMethods(ClassNode.java:842)
    at org.codehaus.groovy.ast.ClassNode.getMethods(ClassNode.java:857)
    at org.spockframework.compiler.SpecialMethodCall.checkIsConditionBlock(SpecialMethodCall.java:194)
    at org.spockframework.compiler.SpecialMethodCall.parse(SpecialMethodCall.java:151)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.visitMethodCallExpression(AbstractDeepBlockRewriter.java:110)
    at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:67)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitBinaryExpression(CodeVisitorSupport.java:144)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.doVisitBinaryExpression(AbstractDeepBlockRewriter.java:150)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.visitBinaryExpression(AbstractDeepBlockRewriter.java:98)
    at org.codehaus.groovy.ast.expr.BinaryExpression.visit(BinaryExpression.java:49)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:69)
    at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:195)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.doVisitExpressionStatement(AbstractDeepBlockRewriter.java:146)
    at org.spockframework.compiler.DeepBlockRewriter.doVisitExpressionStatement(DeepBlockRewriter.java:61)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.visitExpressionStatement(AbstractDeepBlockRewriter.java:87)
    at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
    at org.spockframework.compiler.StatementReplacingVisitorSupport.replace(StatementReplacingVisitorSupport.java:44)
    at org.spockframework.compiler.StatementReplacingVisitorSupport.replaceAll(StatementReplacingVisitorSupport.java:59)
    at org.spockframework.compiler.StatementReplacingVisitorSupport.visitBlockStatement(StatementReplacingVisitorSupport.java:72)
    at org.spockframework.compiler.DeepBlockRewriter.visitBlockStatement(DeepBlockRewriter.java:76)
    at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitClosureExpression(CodeVisitorSupport.java:174)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.doVisitClosureExpression(AbstractDeepBlockRewriter.java:158)
    at org.spockframework.compiler.DeepBlockRewriter.doVisitClosureExpression(DeepBlockRewriter.java:70)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.visitClosureExpression(AbstractDeepBlockRewriter.java:137)
    at org.codehaus.groovy.ast.expr.ClosureExpression.visit(ClosureExpression.java:43)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitListOfExpressions(CodeVisitorSupport.java:273)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitTupleExpression(CodeVisitorSupport.java:178)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitArgumentlistExpression(CodeVisitorSupport.java:283)
    at org.codehaus.groovy.ast.expr.ArgumentListExpression.visit(ArgumentListExpression.java:74)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitMethodCallExpression(CodeVisitorSupport.java:131)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.doVisitMethodCallExpression(AbstractDeepBlockRewriter.java:154)
    at org.spockframework.compiler.DeepBlockRewriter.doVisitMethodCallExpression(DeepBlockRewriter.java:86)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.visitMethodCallExpression(AbstractDeepBlockRewriter.java:119)
    at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:67)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:69)
    at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:195)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.doVisitExpressionStatement(AbstractDeepBlockRewriter.java:146)
    at org.spockframework.compiler.DeepBlockRewriter.doVisitExpressionStatement(DeepBlockRewriter.java:61)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.visitExpressionStatement(AbstractDeepBlockRewriter.java:87)
    at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
    at org.spockframework.compiler.StatementReplacingVisitorSupport.replace(StatementReplacingVisitorSupport.java:44)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.visit(AbstractDeepBlockRewriter.java:71)
    at org.spockframework.compiler.DeepBlockRewriter.visit(DeepBlockRewriter.java:49)
    at org.spockframework.compiler.SpecRewriter.visitAnyBlock(SpecRewriter.java:316)
    at org.spockframework.compiler.model.SetupBlock.accept(SetupBlock.java:32)
    at org.spockframework.compiler.model.Method.accept(Method.java:70)
    at org.spockframework.compiler.model.Spec.accept(Spec.java:113)
    at org.spockframework.compiler.SpockTransform$Impl.processSpec(SpockTransform.java:77)
    at org.spockframework.compiler.SpockTransform$Impl.visit(SpockTransform.java:64)
    at org.spockframework.compiler.SpockTransform.visit(SpockTransform.java:47)
    at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:319)
    at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:900)
    at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:564)
    at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:540)
    at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:517)
    at org.jetbrains.groovy.compiler.rt.GroovyCompilerWrapper.compile(GroovyCompilerWrapper.java:54)
    at org.jetbrains.groovy.compiler.rt.DependentGroovycRunner.runGroovyc(DependentGroovycRunner.java:87)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: org.xmlpull.v1.XmlPullParser
    at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:148)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 73 more
Information:Modules "xdstools3", "tk-apis", "repo-support", "sim-support", "soap-support" and 6 others were fully rebuilt due to project configuration/dependencies changes
Information:Compilation completed with 1 error and 75 warnings in 2 min 5 sec
Information:1 error
Information:75 warnings
Error:Groovyc: Internal groovyc error: code 1

---
- Bitbucket: https://bitbucket.org/iheos/defunct-toolkit-prototype/issue/157

**Comment by iheos** [comment]
_Original comment by_ **Bill Majurski (Bitbucket: [bmajur](https://bitbucket.org/bmajur), GitHub: Unknown)**:

---

Groovy does a lot of run-time compilation since some of it features are
dynamic.  In this case it looks like it is compiling some of my unit
tests.  One possible cause is the wrong version of groovy (must be 2.0.0)
or a dependency on a different version of spock (groovy junit-like tool).
The only spock version spec should be in tk-deps.

**Comment by iheos** [comment]
_Original comment by_ **Diane Azais (Bitbucket: [dazais](https://bitbucket.org/dazais), GitHub: [dazais](https://github.com/dazais))**:

---

The Spock versions are correct, the only version specified is in tk-deps. I also checked that Spock does not generate version conflicts.

The issue had two causes:

1/  somehow toolkit3 reverted to Groovy 2.1.8. That is an error we fixed earlier and that crept back in. The Groovy version in toolkit3 actually has to be 2.0.0 to be compatible with tk-core. Removing the version does not work, because for some reason toolkit3 is unable to find tk-deps during a maven build. This should be optimized later.

2/  Groovy was not compiling anyway because it has to be on Intellij classpath. I forgot to re-add it as compile dependency after a reimport.

**Comment by iheos** [comment]
_Original comment by_ **Diane Azais (Bitbucket: [dazais](https://bitbucket.org/dazais), GitHub: [dazais](https://github.com/dazais))**:

---

The issue keeps creeping back in. A reinstall of only toolkit2-build in my local maven repository, rebuild of toolkit3, recompile of xdstools3, then dump of browser cache might have fixed it.

Toolkit2-build does not work under Groovy 2.0.0, has to be 2.1.8. So a permanent fix would be to remove all refs to toolkit2-build from toolkit3. Olivier is working on moving the code he needs for that.

**Comment by iheos** [comment]
_Original comment by_ **Diane Azais (Bitbucket: [dazais](https://bitbucket.org/dazais), GitHub: [dazais](https://github.com/dazais))**:

---

This issue is not present on feature/gui but still present on develop.

**Comment by iheos** [comment]
_Original comment by_ **Diane Azais (Bitbucket: [dazais](https://bitbucket.org/dazais), GitHub: [dazais](https://github.com/dazais))**:

---

Most recent stack trace:

Information:Groovyc: java.lang.ClassNotFoundException: org.xmlpull.v1.XmlPullParser
    at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:148)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
    at java.lang.Class.getDeclaredMethods(Class.java:1860)
    at org.codehaus.groovy.vmplugin.v5.Java5.configureClassNode(Java5.java:328)
    at org.codehaus.groovy.ast.ClassNode.lazyClassInit(ClassNode.java:262)
    at org.codehaus.groovy.ast.ClassNode.getDeclaredMethods(ClassNode.java:842)
    at org.codehaus.groovy.ast.ClassNode.getMethods(ClassNode.java:857)
    at org.spockframework.compiler.SpecialMethodCall.checkIsConditionBlock(SpecialMethodCall.java:194)
    at org.spockframework.compiler.SpecialMethodCall.parse(SpecialMethodCall.java:151)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.visitMethodCallExpression(AbstractDeepBlockRewriter.java:110)
    at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:67)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitBinaryExpression(CodeVisitorSupport.java:144)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.doVisitBinaryExpression(AbstractDeepBlockRewriter.java:150)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.visitBinaryExpression(AbstractDeepBlockRewriter.java:98)
    at org.codehaus.groovy.ast.expr.BinaryExpression.visit(BinaryExpression.java:49)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:69)
    at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:195)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.doVisitExpressionStatement(AbstractDeepBlockRewriter.java:146)
    at org.spockframework.compiler.DeepBlockRewriter.doVisitExpressionStatement(DeepBlockRewriter.java:61)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.visitExpressionStatement(AbstractDeepBlockRewriter.java:87)
    at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
    at org.spockframework.compiler.StatementReplacingVisitorSupport.replace(StatementReplacingVisitorSupport.java:44)
    at org.spockframework.compiler.StatementReplacingVisitorSupport.replaceAll(StatementReplacingVisitorSupport.java:59)
    at org.spockframework.compiler.StatementReplacingVisitorSupport.visitBlockStatement(StatementReplacingVisitorSupport.java:72)
    at org.spockframework.compiler.DeepBlockRewriter.visitBlockStatement(DeepBlockRewriter.java:76)
    at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitClosureExpression(CodeVisitorSupport.java:174)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.doVisitClosureExpression(AbstractDeepBlockRewriter.java:158)
    at org.spockframework.compiler.DeepBlockRewriter.doVisitClosureExpression(DeepBlockRewriter.java:70)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.visitClosureExpression(AbstractDeepBlockRewriter.java:137)
    at org.codehaus.groovy.ast.expr.ClosureExpression.visit(ClosureExpression.java:43)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitListOfExpressions(CodeVisitorSupport.java:273)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitTupleExpression(CodeVisitorSupport.java:178)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitArgumentlistExpression(CodeVisitorSupport.java:283)
    at org.codehaus.groovy.ast.expr.ArgumentListExpression.visit(ArgumentListExpression.java:74)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitMethodCallExpression(CodeVisitorSupport.java:131)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.doVisitMethodCallExpression(AbstractDeepBlockRewriter.java:154)
    at org.spockframework.compiler.DeepBlockRewriter.doVisitMethodCallExpression(DeepBlockRewriter.java:86)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.visitMethodCallExpression(AbstractDeepBlockRewriter.java:119)
    at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:67)
    at org.codehaus.groovy.ast.CodeVisitorSupport.visitExpressionStatement(CodeVisitorSupport.java:69)
    at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitExpressionStatement(ClassCodeVisitorSupport.java:195)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.doVisitExpressionStatement(AbstractDeepBlockRewriter.java:146)
    at org.spockframework.compiler.DeepBlockRewriter.doVisitExpressionStatement(DeepBlockRewriter.java:61)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.visitExpressionStatement(AbstractDeepBlockRewriter.java:87)
    at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
    at org.spockframework.compiler.StatementReplacingVisitorSupport.replace(StatementReplacingVisitorSupport.java:44)
    at org.spockframework.compiler.AbstractDeepBlockRewriter.visit(AbstractDeepBlockRewriter.java:71)
    at org.spockframework.compiler.DeepBlockRewriter.visit(DeepBlockRewriter.java:49)
    at org.spockframework.compiler.SpecRewriter.visitAnyBlock(SpecRewriter.java:316)
    at org.spockframework.compiler.model.SetupBlock.accept(SetupBlock.java:32)
    at org.spockframework.compiler.model.Method.accept(Method.java:70)
    at org.spockframework.compiler.model.Spec.accept(Spec.java:113)
    at org.spockframework.compiler.SpockTransform$Impl.processSpec(SpockTransform.java:77)
    at org.spockframework.compiler.SpockTransform$Impl.visit(SpockTransform.java:64)
    at org.spockframework.compiler.SpockTransform.visit(SpockTransform.java:47)
    at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:319)
    at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:900)
    at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:564)
    at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:540)
    at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:517)
    at org.jetbrains.groovy.compiler.rt.GroovyCompilerWrapper.compile(GroovyCompilerWrapper.java:54)
    at org.jetbrains.groovy.compiler.rt.DependentGroovycRunner.runGroovyc(DependentGroovycRunner.java:87)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jetbrains.groovy.compiler.rt.GroovycRunner.main(GroovycRunner.java:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:130)

**Comment by iheos** [comment]
_Original comment by_ **Diane Azais (Bitbucket: [dazais](https://bitbucket.org/dazais), GitHub: [dazais](https://github.com/dazais))**:

---

I tried:
mvn clean, delete gov folder inside local .m2 repository, mvn clean install skiptest on package engine (tests do not pass but it builds), mvn clean install on toolkit3.

Still getting the same error.

**Comment by iheos** [comment]
_Original comment by_ **Bill Majurski (Bitbucket: [bmajur](https://bitbucket.org/bmajur), GitHub: Unknown)**:

---

I cannot reproduce this error.  I ran everything including tests from
within IntelliJ and it works fine for me.  I also ran it from normal
command line and it is ok there too on my machine.
