### ISSUE TITLE
Feedback from NA2015 - Wrong repository uid (oid) formatting error

### ISSUE THREAD

**Issue by iheos** [iheos/iheos-toolkit3#213]
Originally reported by: **Olivier Herrmann (Bitbucket: [oherrmann](https://bitbucket.org/oherrmann), GitHub: [oherrmann](https://github.com/oherrmann))**

---

There is a problem when using connectathon tool     XDS.b_Registry_Folder_Handling for [test instance 46257 in Gazelle](http://10.242.100.100/gazelle-na/testing/test/test/TestInstance.seam?id=46257). 
The vendor claims that the repository unique id that the nist xds tool is sending in the register document set transaction does not conform to the validation of a properly formatted OID. Their system is checking for that OID to be valid and it is not.

Here is the beginning of the stacktrace:
Status: Failure
Using TLS
Not using SAML
Site: OTHER_Sandlot
Parameters:
...$patientid$: IHERED-2071^^^&1.3.6.1.4.1.21367.13.20.1000&ISO
Starting
Error Exception thrown: gov.nist.toolkit.xdsexception.XdsInternalException
Error XDSRepositoryError : Improperly formatted Object Identifier String - 1.234.2.3.4.5 : 
gov.nist.toolkit.xdsexception.XdsInternalException: Error XDSRepositoryError : Improperly formatted Object Identifier String - 1.234.2.3.4.5 : 
at gov.nist.toolkit.testengine.BasicContext.error(BasicContext.java:120)
at gov.nist.toolkit.testengine.StepContext.set_error(StepContext.java:132)
at gov.nist.toolkit.testengine.transactions.BasicTransaction.soapCall(BasicTransaction.java:1194)
at gov.nist.toolkit.testengine.transactions.RegisterTransaction.run(RegisterTransaction.java:52)
at gov.nist.toolkit.testengine.transactions.BasicTransaction.doRun(BasicTransaction.java:183)
at gov.nist.toolkit.testengine.StepContext.run(StepContext.java:358)
at gov.nist.toolkit.testengine.PlanContext.run(PlanContext.java:233)
at gov.nist.toolkit.testengine.XdsTest.runAndReturnLogs(XdsTest.java:709)
at gov.nist.toolkit.testengine.Xdstest2.run(Xdstest2.java:309)
at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runUtilityTest(XdsTestServiceManager.java:195)
at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.xdstest(XdsTestServiceManager.java:92)
at gov.nist.toolkit.session.server.services.FolderValidation.run(FolderValidation.java:29)
at gov.nist.toolkit.session.server.serviceManager.QueryServiceManager.folderValidation(QueryServiceManager.java:86)
at gov.nist.toolkit.xdstools2.server.ToolkitServiceImpl.folderValidation(ToolkitServiceImpl.java:178)
at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:616)
at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:710)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:210)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:174)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
at org.apache.catalina.valves.FastCommonAccessLogValve.invoke(FastCommonAccessLogValve.java:482)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:542)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:151)
at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:870)
at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)
at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)
at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)
at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:685)
at java.lang.Thread.run(Thread.java:679)
Error 
Validator: Found 0 Associations instead of 1
....

---
- Bitbucket: https://bitbucket.org/iheos/defunct-toolkit-prototype/issue/213

**Comment by iheos** [comment]
_Original comment by_ **Bill Majurski (Bitbucket: [bmajur](https://bitbucket.org/bmajur), GitHub: Unknown)**:

---

This comes up in the folder test required at CAT

**Comment by iheos** [comment]
_Original comment by_ **Bill Majurski (Bitbucket: [bmajur](https://bitbucket.org/bmajur), GitHub: Unknown)**:

---

Moved to v2 bug tracker
