### ISSUE TITLE
Feedback from EU2015 - Folder test fails because of similar times for folder creation and folder update

### ISSUE THREAD

**Issue by iheos** [iheos/iheos-toolkit3#240]
Originally reported by: **Diane Azais (Bitbucket: [dazais](https://bitbucket.org/dazais), GitHub: [dazais](https://github.com/dazais))**

---

Issue in xds b folder test:

We had a few occurrences of document creation time and folder update time being the same when the participant system only supports time up to the second. This fails because the spec has an assertion that requires the folder update time to be different from the folder creation time.

---
- Bitbucket: https://bitbucket.org/iheos/defunct-toolkit-prototype/issue/240

**Comment by iheos** [comment]
_Original comment by_ **Bill Majurski (Bitbucket: [bmajur](https://bitbucket.org/bmajur), GitHub: Unknown)**:

---

Very curious.  The folder update time test inserts 4 or 5 seconds delay
between folder creation and folder update because many systems only record
to the second.  Please document which folder test you are describing and
capture the request and response messages from toolkit.  I suspect
something else is going on here.

**Comment by iheos** [comment]
_Original comment by_ **Diane Azais (Bitbucket: [dazais](https://bitbucket.org/dazais), GitHub: [dazais](https://github.com/dazais))**:

---

Test: XDS.b_Registry_Folder_Handling

# 11999

Stack trace:

Status: Failure
Using TLS
Not using SAML
Site: OTHER_Meddex
Parameters:
...$patientid$: IHERED-0001^^^&1.3.6.1.4.1.21367.13.20.1000&ISO
Starting
Error AssertionEngine: exception gov.nist.toolkit.xdsexception.XdsInternalException: Error AssertionEngine: assertion dateUpdated failed - detailed result is false
Assertion is 
'20150422084800' != '20150422084800'
AssertionEngine: assertion dateUpdated left side value is '20150422084800'
AssertionEngine: assertion dateUpdated right side value is '20150422084800'
AssertionEngine: operator is !=
Exception thrown: gov.nist.toolkit.xdsexception.XdsInternalException
Error AssertionEngine: assertion dateUpdated failed - detailed result is false
Assertion is 
'20150422084800' != '20150422084800'
AssertionEngine: assertion dateUpdated left side value is '20150422084800'
AssertionEngine: assertion dateUpdated right side value is '20150422084800'
AssertionEngine: operator is !=
gov.nist.toolkit.xdsexception.XdsInternalException: Error AssertionEngine: assertion dateUpdated failed - detailed result is false
Assertion is 
'20150422084800' != '20150422084800'
AssertionEngine: assertion dateUpdated left side value is '20150422084800'
AssertionEngine: assertion dateUpdated right side value is '20150422084800'
AssertionEngine: operator is !=
at gov.nist.toolkit.testengine.BasicContext.error(BasicContext.java:120)
at gov.nist.toolkit.testengine.StepContext.set_error(StepContext.java:132)
at gov.nist.toolkit.testengine.StepContext.fail(StepContext.java:155)
at gov.nist.toolkit.testengine.AssertionEngine.run(AssertionEngine.java:196)
at gov.nist.toolkit.testengine.transactions.BasicTransaction.runAssertionEngine(BasicTransaction.java:1055)
at gov.nist.toolkit.testengine.StepContext.run(StepContext.java:364)
at gov.nist.toolkit.testengine.PlanContext.run(PlanContext.java:233)
at gov.nist.toolkit.testengine.XdsTest.runAndReturnLogs(XdsTest.java:709)
at gov.nist.toolkit.testengine.Xdstest2.run(Xdstest2.java:309)
at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runUtilityTest(XdsTestServiceManager.java:195)
at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.xdstest(XdsTestServiceManager.java:92)
at gov.nist.toolkit.session.server.services.FolderValidation.run(FolderValidation.java:29)
at gov.nist.toolkit.session.server.serviceManager.QueryServiceManager.folderValidation(QueryServiceManager.java:86)
at gov.nist.toolkit.xdstools2.server.ToolkitServiceImpl.folderValidation(ToolkitServiceImpl.java:178)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:641)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Error AssertionEngine: exception gov.nist.toolkit.xdsexception.XdsInternalException: Error AssertionEngine: assertion dateUpdated failed - detailed result is false
Assertion is 
'20150422084800' < '20150422084800'

Exception thrown: gov.nist.toolkit.xdsexception.XdsInternalException
Error AssertionEngine: assertion dateUpdated failed - detailed result is false
Assertion is 
'20150422084800' < '20150422084800'

gov.nist.toolkit.xdsexception.XdsInternalException: Error AssertionEngine: assertion dateUpdated failed - detailed result is false
Assertion is 
'20150422084800' < '20150422084800'

at gov.nist.toolkit.testengine.BasicContext.error(BasicContext.java:120)
at gov.nist.toolkit.testengine.StepContext.set_error(StepContext.java:132)
at gov.nist.toolkit.testengine.StepContext.fail(StepContext.java:155)
at gov.nist.toolkit.testengine.AssertionEngine.run(AssertionEngine.java:196)
at gov.nist.toolkit.testengine.transactions.BasicTransaction.runAssertionEngine(BasicTransaction.java:1055)
at gov.nist.toolkit.testengine.StepContext.run(StepContext.java:364)
at gov.nist.toolkit.testengine.PlanContext.run(PlanContext.java:233)
at gov.nist.toolkit.testengine.XdsTest.runAndReturnLogs(XdsTest.java:709)
at gov.nist.toolkit.testengine.Xdstest2.run(Xdstest2.java:309)
at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.runUtilityTest(XdsTestServiceManager.java:195)
at gov.nist.toolkit.session.server.serviceManager.XdsTestServiceManager.xdstest(XdsTestServiceManager.java:92)
at gov.nist.toolkit.session.server.services.FolderValidation.run(FolderValidation.java:29)
at gov.nist.toolkit.session.server.serviceManager.QueryServiceManager.folderValidation(QueryServiceManager.java:86)
at gov.nist.toolkit.xdstools2.server.ToolkitServiceImpl.folderValidation(ToolkitServiceImpl.java:178)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:641)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987)
at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)
at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)

[..]

at gov.nist.toolkit.testengine.AssertionEngine.run(AssertionEngine.java:204)

[..]

**Comment by iheos** [comment]
_Original comment by_ **Bill Majurski (Bitbucket: [bmajur](https://bitbucket.org/bmajur), GitHub: Unknown)**:

---

Stack trace is helpful but the request/response message from the folder
create and folder update messages will be necessary.

**Comment by iheos** [comment]
_Original comment by_ **Bill Majurski (Bitbucket: [bmajur](https://bitbucket.org/bmajur), GitHub: Unknown)**:

---

Cannot reproduce.  The test inserts a 4-5 second delay to account for systems that only manage time to the second.  

Moved to new v2 tracker
