### ISSUE TITLE
saml resource MA1092 throws exception

### ISSUE THREAD

**Issue by iheos** [iheos/iheos-toolkit3#25]
Originally reported by: **antoine gerardin (Bitbucket: [agerardin](https://bitbucket.org/agerardin), GitHub: [agerardin](https://github.com/agerardin))**

---

One of the saml test fails

4047 INFO  gov.nist.toolkit.wsseTool.api.WsseHeaderValidator  - run validation with -id : MA1092 -name : resource 
 requirements checked are: [131, 134]
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:189)
    at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
    at gov.nist.toolkit.wsseTool.api.WsseHeaderValidator.runValidation(WsseHeaderValidator.groovy:138)
    at gov.nist.toolkit.wsseTool.api.WsseHeaderValidator.this$2$runValidation(WsseHeaderValidator.groovy)
    at gov.nist.toolkit.wsseTool.api.WsseHeaderValidator$this$2$runValidation.callCurrent(Unknown Source)
    at gov.nist.toolkit.wsseTool.api.WsseHeaderValidator.validate(WsseHeaderValidator.groovy:102)
    at gov.nist.toolkit.wsseTool.api.WsseHeaderValidator$validate$0.callCurrent(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
    at gov.nist.toolkit.wsseTool.api.WsseHeaderValidator$validate$0.callCurrent(Unknown Source)
    at gov.nist.toolkit.wsseTool.api.WsseHeaderValidator.validate(WsseHeaderValidator.groovy:60)
    at gov.nist.toolkit.wsseTool.api.WsseHeaderValidator$validate.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
    at gov.nist.toolkit.wsseTool.validation.ValidationTest.runBatch(ValidationTest.groovy:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.NullPointerException: Cannot invoke method text() on null object
    at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:77)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
    at gov.nist.toolkit.wsseTool.validation.AuthzDecisionStatementVal.resource(AuthzDecisionStatementVal.groovy:68)
    ... 50 more

---
- Bitbucket: https://bitbucket.org/iheos/defunct-toolkit-prototype/issue/25

**Comment by iheos** [comment]
_Original comment by_ **antoine gerardin (Bitbucket: [agerardin](https://bitbucket.org/agerardin), GitHub: [agerardin](https://github.com/agerardin))**:

---

Extra parameter "To" passed to the SecurityContext.

It seems not very flexible to pass parameters one by one to the underlying code but it seems to be the less invasive style of interation and the easiest one to test. The client has the burden to provide the right parameters.
