### ISSUE TITLE
Creating a folder based asset as a child of an asset is broken

### ISSUE THREAD

**Issue by iheos** [iheos/iheos-toolkit3#88]
Originally reported by: **Bill Majurski (Bitbucket: [bmajur](https://bitbucket.org/bmajur), GitHub: Unknown)**

---

I can create a folder based asset if the parent is the repository.  If the parent is an asset then the following error is presented:

java.lang.NullPointerException
    at gov.nist.hit.ds.repository.simple.FolderManager.makeFolder(FolderManager.java:61)
    at gov.nist.hit.ds.repository.simple.SimpleAsset.addChild(SimpleAsset.java:593)
    at gov.nist.hit.ds.eventLog.EventFactory.buildEvent(EventFactory.groovy:34)
    at gov.nist.hit.ds.simSupport.utilities.SimUtils.runTransaction(SimUtils.groovy:84)
    at gov.nist.hit.ds.dsSims.reg.RegisterTransactionTest.runit(RegisterTransactionTest.groovy:77)

---
- Bitbucket: https://bitbucket.org/iheos/defunct-toolkit-prototype/issue/88

**Comment by iheos** [comment]
_Original comment by_ **Sunil Bhaskarla (Bitbucket: [skbhaskarla](https://bitbucket.org/skbhaskarla), GitHub: [skbhaskarla](https://github.com/skbhaskarla))**:

---

Fix issue 88: Add complex asset, one containing folders, to another top level parent
